name: DVC Data Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dvc_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Pull Latest DVC Data
        run: dvc pull

      - name: Track Raw Data
        run: |
          dvc add data/raw/*
          dvc add data/processed/*

      - name: Push to DVC Remote
        run: dvc push

      - name: Commit DVC changes
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/huzaifa678/ETL-pipeline-project.git
          git add data/*.dvc 
          git commit -m "CI: update DVC tracked files" || echo "No changes to commit"
          git push origin main
        env:
            PAT_TOKEN: ${{ secrets.ETL_PAT_TOKEN }}